import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";
import { exec } from "child_process";
import { promisify } from "util";
import { S3Client, PutObjectCommand, DeleteObjectCommand } from "@aws-sdk/client-s3";

const execAsync = promisify(exec);

const app = express();
const PORT = 3000;

app.use(express.json());

// API: Check PHP version
app.post("/api/check-php", async (req, res) => {
  try {
    const { phpPath } = req.body;
    if (!phpPath) {
      return res.status(400).json({ success: false, error: "PHP path is required" });
    }
    
    const { stdout } = await execAsync(`"${phpPath}" -v`);
    const versionLine = stdout.split('\\n')[0];
    res.json({ success: true, version: versionLine });
  } catch (err: any) {
    res.json({ success: false, error: err.message || "Failed to execute PHP at the specified path." });
  }
});

// API: Test S3 Connection & Write Permissions
app.post("/api/test-s3", async (req, res) => {
  try {
    const { s3Bucket, s3Region, s3AccessKey, s3SecretKey, s3Endpoint } = req.body;
    if (!s3Bucket || !s3Region || !s3AccessKey || !s3SecretKey) {
      return res.status(400).json({ success: false, error: "Missing required S3 credentials." });
    }

    const client = new S3Client({
      region: s3Region,
      endpoint: s3Endpoint || undefined,
      credentials: {
        accessKeyId: s3AccessKey,
        secretAccessKey: s3SecretKey,
      },
    });

    const testKey = `_aisensy_test_upload_${Date.now()}.txt`;

    // 1. Test Write Permission (Dry-run upload)
    await client.send(new PutObjectCommand({
      Bucket: s3Bucket,
      Key: testKey,
      Body: "This is a temporary test file generated by AISensy WhatsApp Sync to verify write permissions.",
      ContentType: "text/plain"
    }));
    
    // 2. Clean up the test file
    await client.send(new DeleteObjectCommand({
      Bucket: s3Bucket,
      Key: testKey
    }));
    
    res.json({ success: true, message: "Successfully verified upload & write permissions!" });
  } catch (err: any) {
    res.json({ success: false, error: err.message || "Failed to verify S3 write permissions." });
  }
});

// API: Generate wrapper configurations & converted PHP daemon
app.post("/api/generate-wrapper", (req, res) => {
  try {
    const {
      serviceName = "WhatsAppSyncService",
      displayName = "WhatsApp PHP Sync Daemon",
      description = "Background Windows Service for syncing WhatsApp messages and webhooks using PHP ODBC",
      phpPath = "C:\\php\\php.exe",
      scriptPath = "C:\\whatsapp-sync\\whatsapp-daemon.php",
      workingDirectory = "C:\\whatsapp-sync",
      enableCloudUpload = false,
      localPdfPath = "C:\\ftproot\\Whatsapp",
      s3Endpoint = "",
      s3Bucket = "",
      s3Region = "auto",
      s3AccessKey = "",
      s3SecretKey = "",
      s3PublicUrl = "",
      s3PresignedUrl = false,
      s3PresignedExpiry = "604800",
      s3MaxRetries = 3,
      s3RetryBackoff = true,
      s3InitialBackoffMs = 1000,
      s3BackoffMultiplier = 2,
      syncRecursive = false,
      excludeExtensions = "",
      logMode = "roll-by-size",
      startMode = "Automatic",
      onFailure = "restart",
      delaySeconds = "10",
      dependencies = "",
      generateHealthCheck = false,
      odbcDriver = "{SQL Server Native Client 11.0}"
    } = req.body;

    const dependTags = dependencies
      .split(',')
      .map((d: string) => d.trim())
      .filter((d: string) => d.length > 0)
      .map((d: string) => `  <depend>${d}</depend>`)
      .join('\n');

    // 1. WinSW XML Configuration
    const winswXml = `<service>
  <id>${serviceName}</id>
  <name>${displayName}</name>
  <description>${description}</description>
  <executable>${phpPath}</executable>
  <arguments>"${scriptPath}"</arguments>
  <log mode="${logMode}">
    <sizeThreshold>10240</sizeThreshold>
    <keepFiles>10</keepFiles>
  </log>
  <workingdirectory>${workingDirectory}</workingdirectory>
  <startmode>${startMode}</startmode>
${dependTags ? dependTags + '\n' : ''}  <onfailure action="${onFailure}" delay="${delaySeconds}sec"/>
  <resetfailure>1 hour</resetfailure>
  <env name="APP_ENV" value="production" />
  <env name="PHP_CLI_SERVER_WORKERS" value="4" />
</service>`;

    const nssmDepends = dependencies
      .split(',')
      .map((d: string) => d.trim())
      .filter((d: string) => d.length > 0)
      .join(' ');

    // 2. NSSM Batch Installer
    const nssmBatch = `@echo off
TITLE Install ${displayName} as Windows Service
color 0b
echo ========================================================
echo Installing ${displayName} via NSSM...
echo ========================================================

net session >nul 2>&1
if %errorLevel% neq 0 (
    echo [ERROR] Please run this script as Administrator!
    pause
    exit /b 1
)

REM Check if nssm is available
where nssm >nul 2>&1
if %errorLevel% equ 0 (
    set "NSSM_BIN=nssm"
) else if exist "%~dp0nssm.exe" (
    set "NSSM_BIN=%~dp0nssm.exe"
) else if exist "%~dp0win64\nssm.exe" (
    set "NSSM_BIN=%~dp0win64\nssm.exe"
) else (
    echo [INFO] nssm.exe was not found in PATH or the current folder.
    echo [INFO] Attempting to auto-download 64-bit nssm.exe via PowerShell...
    powershell -NoProfile -ExecutionPolicy Bypass -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; $zip = Join-Path $env:TEMP 'nssm.zip'; try { Invoke-WebRequest -Uri 'https://nssm.cc/release/nssm-2.24.zip' -OutFile $zip -UseBasicParsing; Expand-Archive -Path $zip -DestinationPath (Join-Path $env:TEMP 'nssm_temp') -Force; Copy-Item (Join-Path $env:TEMP 'nssm_temp\nssm-2.24\win64\nssm.exe') -Destination '%~dp0nssm.exe' -Force; Remove-Item $zip -Force -ErrorAction SilentlyContinue; Remove-Item (Join-Path $env:TEMP 'nssm_temp') -Recurse -Force -ErrorAction SilentlyContinue; exit 0 } catch { exit 1 }"
    if exist "%~dp0nssm.exe" (
        echo [SUCCESS] nssm.exe downloaded successfully.
        set "NSSM_BIN=%~dp0nssm.exe"
    ) else (
        echo.
        echo [ERROR] nssm.exe is required to register this Windows service.
        echo Automatic download failed or this machine does not have internet access.
        echo.
        echo -------------------------------------------------------------
        echo QUICK MANUAL FIX (takes 1 minute):
        echo 1. Download NSSM from: https://nssm.cc/download
        echo 2. Open the downloaded zip, go to folder 'win64'
        echo 3. Copy 'nssm.exe' into this exact folder:
        echo    %~dp0
        echo 4. Run this install-service.bat script again as Administrator.
        echo -------------------------------------------------------------
        echo.
        pause
        exit /b 1
    )
)

echo Registering Windows Service "${serviceName}"...
"%NSSM_BIN%" install "${serviceName}" "${phpPath}"
if %errorLevel% neq 0 (
    echo.
    echo [ERROR] Failed to register Windows Service "${serviceName}".
    echo Please verify that the service name does not already exist and PHP exists at:
    echo "${phpPath}"
    echo.
    pause
    exit /b %errorLevel%
)

"%NSSM_BIN%" set "${serviceName}" AppParameters """${scriptPath}"""
"%NSSM_BIN%" set "${serviceName}" AppDirectory "${workingDirectory}"
"%NSSM_BIN%" set "${serviceName}" DisplayName "${displayName}"
"%NSSM_BIN%" set "${serviceName}" Description "${description}"
${nssmDepends ? `"%NSSM_BIN%" set "${serviceName}" DependOnService ${nssmDepends}` : ''}
"%NSSM_BIN%" set "${serviceName}" Start SERVICE_AUTO_START
"%NSSM_BIN%" set "${serviceName}" AppStdout "${workingDirectory}\\logs\\service-stdout.log"
"%NSSM_BIN%" set "${serviceName}" AppStderr "${workingDirectory}\\logs\\service-stderr.log"
"%NSSM_BIN%" set "${serviceName}" AppRotateFiles 1
"%NSSM_BIN%" set "${serviceName}" AppRotateBytes 10485760

echo ========================================================
echo Service "${serviceName}" configured successfully!
echo Starting service now...
net start "${serviceName}"
if %errorLevel% neq 0 (
    echo [WARNING] Service failed to start immediately. Check log at:
    echo "${workingDirectory}\\logs\\service-stderr.log"
) else (
    echo [SUCCESS] Service "${serviceName}" is now RUNNING!
)
pause
`;

    // 2b. NSSM Batch Uninstaller
    const nssmUninstallBatch = `@echo off
TITLE Uninstall ${displayName}
color 0c
echo ========================================================
echo Uninstalling ${displayName}...
echo ========================================================

net session >nul 2>&1
if %errorLevel% neq 0 (
    echo [ERROR] Please run this script as Administrator!
    pause
    exit /b 1
)

where nssm >nul 2>&1
if %errorLevel% equ 0 (
    set "NSSM_BIN=nssm"
) else if exist "%~dp0nssm.exe" (
    set "NSSM_BIN=%~dp0nssm.exe"
) else if exist "%~dp0win64\nssm.exe" (
    set "NSSM_BIN=%~dp0win64\nssm.exe"
) else (
    echo [ERROR] nssm.exe not found in PATH or in the current directory.
    pause
    exit /b 1
)

echo Stopping the service...
"%NSSM_BIN%" stop "${serviceName}"

echo Removing the service...
"%NSSM_BIN%" remove "${serviceName}" confirm

echo ========================================================
echo Service "${serviceName}" removed successfully.
pause
`;

    // 3. Converted PHP Daemon Script (Adapted from user's script for continuous Windows Service CLI execution)
    const phpDaemonCode = `<?php
/**
 * WhatsApp PHP Sync Daemon for Windows Service
 * Converted from web-refresh script to a robust background CLI loop.
 */

// Disable execution time limit & enable high memory limit for daemon
set_time_limit(0);
ini_set('memory_limit', '1024M');

// Ensure log directory exists
$logDir = __DIR__ . '/logs';
if (!file_exists($logDir)) {
    mkdir($logDir, 0777, true);
}
$logFile = $logDir . '/daemon.log';

function writeLog($message) {
    global $logFile;
    $timestamp = date('Y-m-d H:i:s');
    $logMessage = "[{$timestamp}] {$message}" . PHP_EOL;
    file_put_contents($logFile, $logMessage, FILE_APPEND);
    echo $logMessage;
}

${syncRecursive ? `
// Recursive Directory Search Feature
function findFileRecursive($dir, $filename, $excludeExtsStr) {
    if (!is_dir($dir)) return false;
    $iterator = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($dir));
    $excludeArr = array_filter(array_map('trim', explode(',', $excludeExtsStr)));
    
    foreach ($iterator as $file) {
        if ($file->isDir()) continue;
        
        $ext = '.' . strtolower($file->getExtension());
        if (!empty($excludeArr) && in_array($ext, $excludeArr)) {
            continue;
        }
        
        $nameNoExt = pathinfo($file->getFilename(), PATHINFO_FILENAME);
        if ($nameNoExt === $filename) {
            return $file->getPathname();
        }
    }
    return false;
}
` : ''}

${enableCloudUpload ? `
// S3 Cloud Storage Upload Function with Automatic Retry & Exponential Backoff
function uploadToS3($filePath, $objectKey) {
    $bucket = "${s3Bucket}";
    $region = "${s3Region}";
    $accessKey = "${s3AccessKey}";
    $secretKey = "${s3SecretKey}";
    $endpoint = "${s3Endpoint}";
    $publicBase = "${s3PublicUrl}";
    $maxRetries = intval("${s3MaxRetries ?? 3}");
    $useBackoff = ${s3RetryBackoff ? 'true' : 'false'};
    $initialBackoffMs = intval("${s3InitialBackoffMs ?? 1000}");
    $backoffMultiplier = floatval("${s3BackoffMultiplier ?? 2}");
    
    if (!file_exists($filePath)) {
        writeLog("S3 Upload Error: File not found locally - {$filePath}");
        return false;
    }

    $attempt = 0;
    while ($attempt <= $maxRetries) {
        $attempt++;
        if ($attempt > 1) {
            writeLog("Retrying S3 upload for {$objectKey} (Attempt {$attempt} of " . ($maxRetries + 1) . ")...");
        }

        $host = empty($endpoint) ? "{$bucket}.s3.{$region}.amazonaws.com" : parse_url($endpoint, PHP_URL_HOST);
        
        if (!empty($endpoint)) {
             $url = rtrim($endpoint, '/') . "/{$bucket}/{$objectKey}";
             $canonicalUri = "/{$bucket}/{$objectKey}";
        } else {
             $url = "https://{$host}/{$objectKey}";
             $canonicalUri = "/{$objectKey}";
        }
        
        $payload = file_get_contents($filePath);
        $amzDate = gmdate('Ymd\\\\THis\\\\Z');
        $dateStamp = gmdate('Ymd');
        $contentType = 'application/pdf';
        
        $canonicalQuery = '';
        $payloadHash = hash('sha256', $payload);
        $canonicalHeaders = "host:{$host}\\nx-amz-content-sha256:{$payloadHash}\\nx-amz-date:{$amzDate}\\n";
        $signedHeaders = 'host;x-amz-content-sha256;x-amz-date';
        
        $canonicalRequest = "PUT\\n{$canonicalUri}\\n{$canonicalQuery}\\n{$canonicalHeaders}\\n{$signedHeaders}\\n{$payloadHash}";
        
        $algorithm = 'AWS4-HMAC-SHA256';
        $credentialScope = "{$dateStamp}/{$region}/s3/aws4_request";
        $stringToSign = "{$algorithm}\\n{$amzDate}\\n{$credentialScope}\\n" . hash('sha256', $canonicalRequest);
        
        $kSecret = 'AWS4' . $secretKey;
        $kDate = hash_hmac('sha256', $dateStamp, $kSecret, true);
        $kRegion = hash_hmac('sha256', $region, $kDate, true);
        $kService = hash_hmac('sha256', 's3', $kRegion, true);
        $kSigning = hash_hmac('sha256', 'aws4_request', $kService, true);
        
        $signature = hash_hmac('sha256', $stringToSign, $kSigning);
        $authorizationHeader = "{$algorithm} Credential={$accessKey}/{$credentialScope}, SignedHeaders={$signedHeaders}, Signature={$signature}";
        
        $headers = [
            "Authorization: {$authorizationHeader}",
            "x-amz-content-sha256: {$payloadHash}",
            "x-amz-date: {$amzDate}",
            "Content-Type: {$contentType}"
        ];
        
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PUT');
        curl_setopt($ch, CURLOPT_POSTFIELDS, $payload);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_TIMEOUT, 30);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false); 
        $response = curl_exec($ch);
        $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        $curlErr = curl_error($ch);
        curl_close($ch);
        
        if ($httpCode >= 200 && $httpCode < 300) {
            ${s3PresignedUrl ? `return getPresignedUrl($objectKey);` : `
            if (!empty($publicBase)) {
                return rtrim($publicBase, '/') . "/{$objectKey}";
            }
            return $url;
            `}
        }

        writeLog("S3 Upload Failed on attempt {$attempt}. HTTP: {$httpCode}, cURL Error: {$curlErr}, Response: {$response}");
        
        if ($attempt <= $maxRetries) {
            $delayMs = $useBackoff ? intval($initialBackoffMs * pow($backoffMultiplier, $attempt - 1)) : $initialBackoffMs;
            $jitter = mt_rand(0, intval($delayMs * 0.15));
            $totalSleepMs = $delayMs + $jitter;
            writeLog("Backing off for {$totalSleepMs}ms before next retry attempt...");
            usleep($totalSleepMs * 1000);
        }
    }

    writeLog("S3 Upload aborted for {$objectKey} after " . ($maxRetries + 1) . " attempts.");
    return false;
}

${s3PresignedUrl ? `
// Generate S3 Presigned GET URL
function getPresignedUrl($objectKey) {
    $bucket = "${s3Bucket}";
    $region = "${s3Region}";
    $accessKey = "${s3AccessKey}";
    $secretKey = "${s3SecretKey}";
    $endpoint = "${s3Endpoint}";
    $expires = ${s3PresignedExpiry};
    
    $host = empty($endpoint) ? "{$bucket}.s3.{$region}.amazonaws.com" : parse_url($endpoint, PHP_URL_HOST);
    
    if (!empty($endpoint)) {
         $urlBase = rtrim($endpoint, '/');
         $canonicalUri = "/{$bucket}/{$objectKey}";
    } else {
         $urlBase = "https://{$host}";
         $canonicalUri = "/{$objectKey}";
    }
    
    $amzDate = gmdate('Ymd\\\\THis\\\\Z');
    $dateStamp = gmdate('Ymd');
    
    $credentialScope = "{$dateStamp}/{$region}/s3/aws4_request";
    
    $encodedCredential = rawurlencode("{$accessKey}/{$credentialScope}");
    $canonicalQuery = "X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential={$encodedCredential}&X-Amz-Date={$amzDate}&X-Amz-Expires={$expires}&X-Amz-SignedHeaders=host";
    
    $canonicalHeaders = "host:{$host}\\n";
    $signedHeaders = "host";
    $payloadHash = "UNSIGNED-PAYLOAD";
    
    $canonicalRequest = "GET\\n{$canonicalUri}\\n{$canonicalQuery}\\n{$canonicalHeaders}\\n{$signedHeaders}\\n{$payloadHash}";
    $stringToSign = "AWS4-HMAC-SHA256\\n{$amzDate}\\n{$credentialScope}\\n" . hash('sha256', $canonicalRequest);
    
    $kSecret = 'AWS4' . $secretKey;
    $kDate = hash_hmac('sha256', $dateStamp, $kSecret, true);
    $kRegion = hash_hmac('sha256', $region, $kDate, true);
    $kService = hash_hmac('sha256', 's3', $kRegion, true);
    $kSigning = hash_hmac('sha256', 'aws4_request', $kService, true);
    
    $signature = hash_hmac('sha256', $stringToSign, $kSigning);
    
    return "{$urlBase}{$canonicalUri}?{$canonicalQuery}&X-Amz-Signature={$signature}";
}
` : ''}
` : ''}

writeLog("=== WhatsApp Sync Windows Service Daemon Started ===");

// Database Configuration
$myServer = "DESKTOP-VDGDM3P";
$myUser = "sa";
$myPass = "mgenn@123";
$myDB = "Whatsapp"; 

$pollInterval = 30; // seconds between sync cycles

while (true) {
    try {
        writeLog("Connecting to SQL Server ODBC ({$myServer} / {$myDB}) using driver ${odbcDriver}...");
        $dbhandle = odbc_connect("Driver=${odbcDriver};Server=$myServer;Database=$myDB;", $myUser, $myPass);

        if (!$dbhandle) {
            writeLog("ERROR: ODBC connection failed: " . odbc_errormsg());
            sleep(10);
            continue;
        }

        $today = date('Y-m-d');
        writeLog("Executing sync cycle for date: {$today}");

        // Fetch active companies / hotels
        $smsextra = "select isnull(whatsappBusinessflag,0) as businessflag,
            isnull(IsWhatsapp,0) as whatsappflag,isnull(whatsappaskev,0) as whatsappaskev,isnull(mwhatsapp,0) as mwhatsapp,
            * from usedb where isnull(isactive,0)='1' and isnull(Hotelcode,'')<>''";
        
        $extrastmt = odbc_exec($dbhandle, $smsextra);
        if (!$extrastmt) {
            writeLog("ERROR executing usedb query: " . odbc_errormsg($dbhandle));
            odbc_close($dbhandle);
            sleep($pollInterval);
            continue;
        }

        while ($rowex = odbc_fetch_array($extrastmt)) {
            $myServerin = $rowex['servername'];
            $myDBin = $rowex['dbname'];
            $myUserin = $rowex['userid'];
            $myPassin = $rowex['password'];
            $smsCompany = $rowex['companyname'];
            $smsUsername = $rowex['SMSUsername'] ?? '';
            $whatsapp_access_token = $rowex['whatsapp_access_token'];
            $whatsapp_instance_id = $rowex['whatsapp_instance_id'];
            $Whatsapp_MobileNo = $rowex['Whatsapp_MobileNo'];
            $Whatsapp_hotelcode = $rowex['Hotelcode'];
            $whatsappbusiness = $rowex['businessflag'];
            $whatsappflag = $rowex['whatsappflag'];
            $whatsappaskev = $rowex['whatsappaskev'];
            $mwhatsapp = $rowex['mwhatsapp'];
            $whatsappaskev_token = $rowex['whatsappaskev_token'];

            writeLog("Processing Hotel: {$Whatsapp_hotelcode} ({$smsCompany}) [Biz: {$whatsappbusiness}, Askeva: {$whatsappaskev}, MWhatsApp: {$mwhatsapp}]");

            // Connect to individual hotel DB
            $dbhandlein = odbc_connect("Driver=${odbcDriver};Server=$myServerin;Database=$myDBin;", $myUserin, $myPassin);
            if (!$dbhandlein) {
                writeLog("WARNING: Could not connect to hotel DB {$myDBin} on {$myServerin}");
                continue;
            }

            // 1. AISensy Mode
            if ($whatsappbusiness == "1" && $whatsappflag == "0" && $whatsappaskev == "0" && $mwhatsapp == "0") {
                // Update inactive hotel outbox
                $uqry1 = "Update Outbox set whatsappsmsflg = 1, reason ='In active', notsentflag =1 where msgid in (
                    select msgid from outbox ot 
                    inner join Mas_Hotel mh on ot.HotelCode=mh.HotelCode
                    where CONVERT(varchar(25),datecreated,101)=convert(varchar(25),getdate(),101) and isnull(ot.apiresnotsent,0) = 0
                    and isnull(mh.inactive,0)=1 and isnull(ot.whatsappsmsflg,0) =0 and ot.HotelCode ='" . $Whatsapp_hotelcode . "')";
                @odbc_exec($dbhandlein, $uqry1);

                // Ensure opening balance record for today
                $hotqry = "SELECT DISTINCT m.HotelCode FROM mas_hotel m INNER JOIN whatsappcount_opening w ON m.HotelCode = w.hotel_code WHERE ISNULL(m.HotelCode,'')<>'' AND CAST(w.opdate AS date) < '$today'";
                $hotels = @odbc_exec($dbhandlein, $hotqry);
                if ($hotels) {
                    while ($hotel = odbc_fetch_array($hotels)) {
                        $hotelcode = trim($hotel['HotelCode']);
                        $check_today = "SELECT COUNT(*) AS cnt FROM whatsappcount_opening WHERE hotel_code = '$hotelcode' AND CAST(opdate AS date) = '$today'";
                        $res_check = @odbc_exec($dbhandlein, $check_today);
                        $row_check = $res_check ? odbc_fetch_array($res_check) : null;
                        if ($row_check && $row_check['cnt'] > 0) continue;

                        $qry_latest = "SELECT TOP 1 opbal, clbal, opdate, hotel_code, property_name FROM whatsappcount_opening WHERE hotel_code = '$hotelcode' AND CAST(opdate AS date) < '$today' ORDER BY opdate DESC";
                        $res_latest = @odbc_exec($dbhandlein, $qry_latest);
                        $row_latest = $res_latest ? odbc_fetch_array($res_latest) : null;
                        if (!$row_latest) continue;

                        $opbal = $row_latest['opbal'];
                        $clbal = $row_latest['clbal'];
                        $property_name = $row_latest['property_name'];
                        @odbc_exec($dbhandlein, "INSERT INTO whatsappcount_opening (opbal, clbal, opdate, todate, hotel_code, property_name) VALUES ('$opbal', '$clbal', '$today', '$today', '$hotelcode', '$property_name')");
                    }
                }

                // Process Outbox messages
                $smsobox_WB = "select reason,whatsappsmsflg,ot.HotelCode,* from outbox ot inner join Mas_Hotel mh on ot.HotelCode=mh.HotelCode where CONVERT(varchar(25),datecreated,101)=convert(varchar(25),getdate(),101) and isnull(ot.apiresnotsent,0) = 0 and isnull(mh.inactive,0)=0 and isnull(ot.whatsappsmsflg,0) =0 and ot.HotelCode='" . $Whatsapp_hotelcode . "' order by msgid";
                $outboxstmt_wb = @odbc_exec($dbhandlein, $smsobox_WB);

                if ($outboxstmt_wb) {
                    while ($rowob = odbc_fetch_array($outboxstmt_wb)) {
                        $openqry = "SELECT * FROM whatsappcount_opening WHERE opdate = '".$today."' AND hotel_code = '".$Whatsapp_hotelcode."'";
                        $open = @odbc_exec($dbhandlein, $openqry);
                        $clbal = 0;
                        if ($open) {
                            while ($row = odbc_fetch_array($open)) {
                                $clbal = $row['clbal'];
                            }
                        }

                        $templatename = strtolower($rowob['smstemplateid']);
                        $prefix = substr($rowob['MobileNumber'], 0, 3);
                        $file = $rowob['billno'];
                        $mobnew = ($prefix == '+91') ? preg_replace('/\s+/', '', substr($rowob['MobileNumber'], 1)) : preg_replace('/\s+/', '', $rowob['MobileNumber']);

                        $array = [];
                        $sql1 = "select * from outbox_smsval where msgid='" . $rowob['msgid'] . "' and Variableval <>'99' order by Variableval asc";
                        $res1 = @odbc_exec($dbhandlein, $sql1);
                        if ($res1) {
                            while ($row1 = odbc_fetch_array($res1)) {
                                $val = ($row1['Smsval'] == '') ? ' - ' : ((substr($row1['Smsval'], 0, 10) == '01/01/1900') ? substr($row1['Smsval'], 11, 5) : $row1['Smsval']);
                                array_push($array, '"' . $val . '"');
                            }
                        }

                        ${enableCloudUpload ? `
                        $mediaBlock = '';
                        if ($clbal > 0 && !empty($file)) {
                            $filename = $file;
${syncRecursive ? `
                            $searchDir = "${localPdfPath.replace(/\\/g, '/')}";
                            $filepath = findFileRecursive($searchDir, $filename, "${excludeExtensions || ''}");
` : `
                            $filepath = "${localPdfPath.replace(/\\/g, '/')}/$Whatsapp_hotelcode/$filename.pdf";
`}
                            
                            if ($filepath) {
                                $ext = pathinfo($filepath, PATHINFO_EXTENSION);
                                $objectKey = "$Whatsapp_hotelcode/$filename." . $ext;
                                $publicUrl = uploadToS3($filepath, $objectKey);
                                if ($publicUrl) {
                                    $mediaBlock = ', "media": { "url": "' . $publicUrl . '", "filename": "' . $filename . '.' . $ext . '" }';
                                }
                            }
                        }
                        ` : `
                        // PDF sending disabled as per request
                        $mediaBlock = '';
                        `}

                        if ($clbal > 0) {
                            $payload = '{
                                "apiKey": "' . $whatsapp_access_token . '",
                                "campaignName": "' . $templatename . '",
                                "destination": "' . $mobnew . '",
                                "userName": "' . $smsUsername . '",
                                "source": "VBE",
                                "templateParams": [' . implode(",", $array) . ']' . $mediaBlock . ',
                                "tags": [],
                                "attributes": { "attribute_name": "5" }
                            }';

                            $curl = curl_init();
                            curl_setopt_array($curl, array(
                                CURLOPT_URL => 'https://backend.aisensy.com/campaign/t1/api',
                                CURLOPT_RETURNTRANSFER => true,
                                CURLOPT_TIMEOUT => 30,
                                CURLOPT_CUSTOMREQUEST => 'POST',
                                CURLOPT_POSTFIELDS => $payload,
                                CURLOPT_HTTPHEADER => array('Content-Type: application/json'),
                            ));
                            $response = curl_exec($curl);
                            $curlError = curl_error($curl);
                            curl_close($curl);

                            if ($curlError) {
                                writeLog("AISensy Curl Error for msgid {$rowob['msgid']}: {$curlError}");
                                @odbc_exec($dbhandlein, "Update outbox set whatsappsmsflg='1',notsentflag='1',apiresnotsent=1,reason='Timeout/Error',APIPushdatetime='" . $today . "',APIResponsedatetime='" . date('Y-m-d H:i:s') . "' where msgid='" . $rowob['msgid'] . "'");
                            } else {
                                if (trim($response) == 'Success.') {
                                    writeLog("AISensy Sent successfully for msgid {$rowob['msgid']}");
                                    @odbc_exec($dbhandlein, "Update outbox set whatsappsmsflg='1',notsentflag='0',reason='Success.',pmsreason ='Message Sent',APIPushdatetime='" . $today . "',APIResponsedatetime='" . date('Y-m-d H:i:s') . "' where msgid='" . $rowob['msgid'] . "'");
                                    @odbc_exec($dbhandlein, "update whatsappcount_opening set clbal = isnull(clbal,0)-1 where opdate = '".$today."' and hotel_code ='".$Whatsapp_hotelcode."' and isnull(clbal,0) > 0");
                                } else {
                                    $result = json_decode($response, true);
                                    $errReason = isset($result['errorMessage']) ? $result['errorMessage'] : $response;
                                    writeLog("AISensy Failed for msgid {$rowob['msgid']}: {$errReason}");
                                    @odbc_exec($dbhandlein, "Update outbox set whatsappsmsflg='1',notsentflag='1',reason= '".$errReason."',pmsreason ='',APIPushdatetime='" . $today . "',APIResponsedatetime='" . date('Y-m-d H:i:s') . "' where msgid=" . $rowob['msgid']);
                                }
                            }
                        } else {
                            @odbc_exec($dbhandlein, "Update outbox set whatsappsmsflg='1',notsentflag='1',reason='',APIPushdatetime='" . $today . "',pmsreason ='No Credits Available' where msgid='" . $rowob['msgid'] . "'");
                        }
                    }
                }
            }
            // 2. Microgenn WhatsApp Mode
            else if ($whatsappbusiness == "0" && $whatsappflag == "0" && $whatsappaskev == "0" && $mwhatsapp == "1") {
                $smsobox_WB = "select reason,whatsappsmsflg,ot.HotelCode,* from outbox ot inner join Mas_Hotel mh on ot.HotelCode=mh.HotelCode where CONVERT(varchar(25),datecreated,101)=convert(varchar(25),getdate(),101) and isnull(ot.apiresnotsent,0) = 0 and isnull(mh.inactive,0)=0 and isnull(ot.whatsappsmsflg,0) =0 and ot.HotelCode='" . $Whatsapp_hotelcode . "' order by msgid";
                $outboxstmt_wb = @odbc_exec($dbhandlein, $smsobox_WB);

                if ($outboxstmt_wb) {
                    while ($rowob = odbc_fetch_array($outboxstmt_wb)) {
                        $openqry = "SELECT * FROM whatsappcount_opening WHERE opdate = '".$today."' AND hotel_code = '".$Whatsapp_hotelcode."'";
                        $open = @odbc_exec($dbhandlein, $openqry);
                        $clbal = 0;
                        if ($open) {
                            while ($row = odbc_fetch_array($open)) {
                                $clbal = $row['clbal'];
                            }
                        }

                        $templatename = strtolower($rowob['smstemplateid']);
                        $prefix = substr($rowob['MobileNumber'], 0, 3);
                        $mobnew = ($prefix == '+91') ? preg_replace('/\s+/', '', substr($rowob['MobileNumber'], 1)) : preg_replace('/\s+/', '', $rowob['MobileNumber']);

                        $array = [];
                        $sql1 = "select * from outbox_smsval where msgid='" . $rowob['msgid'] . "' and Variableval <>'99' order by Variableval asc";
                        $res1 = @odbc_exec($dbhandlein, $sql1);
                        if ($res1) {
                            while ($row1 = odbc_fetch_array($res1)) {
                                $val = ($row1['Smsval'] == '') ? ' - ' : ((substr($row1['Smsval'], 0, 10) == '01/01/1900') ? substr($row1['Smsval'], 11, 5) : $row1['Smsval']);
                                array_push($array, '"' . $val . '"');
                            }
                        }

                        if ($clbal > 0) {
                            $payload = '{
                                "apiKey": "' . $whatsapp_access_token . '",
                                "campaignName": "' . $templatename . '",
                                "destination": "' . $mobnew . '",
                                "userName": "' . $smsUsername . '",
                                "source": "PMS",
                                "templateParams": [' . implode(",", $array) . '],
                                "tags": [],
                                "attributes": { "attribute_name": "5" }
                            }';

                            $curl = curl_init();
                            curl_setopt_array($curl, array(
                                CURLOPT_URL => 'https://wa.microgenn.com/api/hms/webhook/send',
                                CURLOPT_RETURNTRANSFER => true,
                                CURLOPT_TIMEOUT => 30,
                                CURLOPT_CUSTOMREQUEST => 'POST',
                                CURLOPT_POSTFIELDS => $payload,
                                CURLOPT_HTTPHEADER => array('Content-Type: application/json'),
                            ));
                            $response = curl_exec($curl);
                            curl_close($curl);

                            $data = json_decode($response, true);
                            if (isset($data['success']) && $data['success'] == true) {
                                $messageId = $data['messageId'] ?? 'Success';
                                writeLog("Microgenn Sent successfully for msgid {$rowob['msgid']}");
                                @odbc_exec($dbhandlein, "Update outbox set whatsappsmsflg='1',notsentflag='0',reason='" . $messageId . "',pmsreason ='Message Sent',APIPushdatetime='" . $today . "',APIResponsedatetime='" . date('Y-m-d H:i:s') . "' where msgid='" . $rowob['msgid'] . "'");
                                @odbc_exec($dbhandlein, "update whatsappcount_opening set clbal = isnull(clbal,0)-1 where opdate = '".$today."' and hotel_code ='".$Whatsapp_hotelcode."' and isnull(clbal,0) > 0");
                            } else {
                                $errRps = $data['errorMessage'] ?? 'Failed';
                                writeLog("Microgenn Failed for msgid {$rowob['msgid']}: {$errRps}");
                                @odbc_exec($dbhandlein, "Update outbox set whatsappsmsflg='1',notsentflag='1',reason= '".$errRps."' ,pmsreason ='',APIPushdatetime='" . $today . "',APIResponsedatetime='" . date('Y-m-d H:i:s') . "' where msgid=" . $rowob['msgid']);
                            }
                        }
                    }
                }
            }
            // 3. Askeva Provider WhatsApp Mode
            else if ($whatsappaskev == "1" && $whatsappflag == "1" && !empty($whatsappaskev_token)) {
                $smsobox_WB = "select reason,whatsappsmsflg,ot.HotelCode,* from outbox ot inner join Mas_Hotel mh on ot.HotelCode=mh.HotelCode where CONVERT(varchar(25),datecreated,101)=convert(varchar(25),getdate(),101) and isnull(ot.apiresnotsent,0) = 0 and isnull(mh.inactive,0)=0 and isnull(ot.whatsappsmsflg,0) =0 and ot.HotelCode='" . $Whatsapp_hotelcode . "' order by msgid";
                $outboxstmt_wb = @odbc_exec($dbhandlein, $smsobox_WB);

                if ($outboxstmt_wb) {
                    while ($rowob = odbc_fetch_array($outboxstmt_wb)) {
                        $openqry = "SELECT * FROM whatsappcount_opening WHERE opdate = '".$today."' AND hotel_code = '".$Whatsapp_hotelcode."'";
                        $open = @odbc_exec($dbhandlein, $openqry);
                        $clbal = 0;
                        if ($open) {
                            while ($row = odbc_fetch_array($open)) {
                                $clbal = $row['clbal'];
                            }
                        }

                        $templatename = strtolower($rowob['smstemplateid']);
                        $prefix = substr($rowob['MobileNumber'], 0, 3);
                        $mobnew = ($prefix == '+91') ? preg_replace('/\s+/', '', substr($rowob['MobileNumber'], 1)) : preg_replace('/\s+/', '', $rowob['MobileNumber']);

                        $array = [];
                        $sql1 = "select * from outbox_smsval where msgid='" . $rowob['msgid'] . "' and Variableval <>'99' order by Variableval asc";
                        $res1 = @odbc_exec($dbhandlein, $sql1);
                        if ($res1) {
                            while ($row1 = odbc_fetch_array($res1)) {
                                $val = ($row1['Smsval'] == '') ? ' - ' : ((substr($row1['Smsval'], 0, 10) == '01/01/1900') ? substr($row1['Smsval'], 11, 5) : $row1['Smsval']);
                                array_push($array, '"' . $val . '"');
                            }
                        }

                        if ($clbal > 0) {
                            $payload = '{
                                "template": "' . $templatename . '",
                                "mobile": "' . $mobnew . '",
                                "parameters": [' . implode(",", $array) . ']
                            }';

                            $curl = curl_init();
                            curl_setopt_array($curl, array(
                                CURLOPT_URL => 'https://waapi.hotelierhms.com/v1/message/send-message?token=' . $whatsappaskev_token,
                                CURLOPT_RETURNTRANSFER => true,
                                CURLOPT_TIMEOUT => 30,
                                CURLOPT_CUSTOMREQUEST => 'POST',
                                CURLOPT_POSTFIELDS => $payload,
                                CURLOPT_HTTPHEADER => array('Content-Type: application/json'),
                            ));
                            $response = curl_exec($curl);
                            curl_close($curl);

                            $data = json_decode($response, true);
                            if (isset($data['success']) && $data['success'] == true) {
                                writeLog("Askeva Sent successfully for msgid {$rowob['msgid']}");
                                @odbc_exec($dbhandlein, "Update outbox set whatsappsmsflg='1',notsentflag='0',reason='Success',pmsreason ='Message Sent',APIPushdatetime='" . $today . "',APIResponsedatetime='" . date('Y-m-d H:i:s') . "' where msgid='" . $rowob['msgid'] . "'");
                                @odbc_exec($dbhandlein, "update whatsappcount_opening set clbal = isnull(clbal,0)-1 where opdate = '".$today."' and hotel_code ='".$Whatsapp_hotelcode."' and isnull(clbal,0) > 0");
                            } else {
                                $errRps = $data['message'] ?? $response;
                                writeLog("Askeva Failed for msgid {$rowob['msgid']}: {$errRps}");
                                @odbc_exec($dbhandlein, "Update outbox set whatsappsmsflg='1',notsentflag='1',reason= '".$errRps."' ,pmsreason ='',APIPushdatetime='" . $today . "',APIResponsedatetime='" . date('Y-m-d H:i:s') . "' where msgid=" . $rowob['msgid']);
                            }
                        }
                    }
                }
            }

            @odbc_close($dbhandlein);
        }

        @odbc_close($dbhandle);
        writeLog("Sync cycle completed. Sleeping for {$pollInterval}s...");

    } catch (Exception \$e) {
        writeLog("DAEMON EXCEPTION: " . \$e->getMessage());
    }

    sleep($pollInterval);
}
?>`;

    // 4. PowerShell Service Management Script
    const psScript = `# Windows Service Management Helper for ${serviceName}
param (
    [Parameter(Mandatory=\$false)]
    [ValidateSet('status','start','stop','restart','logs','uninstall')]
    [string]\$Action = 'status'
)

$ServiceName = "${serviceName}"

switch (\$Action) {
    'status' {
        Get-Service -Name \$ServiceName -ErrorAction SilentlyContinue
    }
    'start' {
        Start-Service -Name \$ServiceName
        Write-Host "Service \$ServiceName started." -ForegroundColor Green
    }
    'stop' {
        Stop-Service -Name \$ServiceName
        Write-Host "Service \$ServiceName stopped." -ForegroundColor Yellow
    }
    'restart' {
        Restart-Service -Name \$ServiceName
        Write-Host "Service \$ServiceName restarted." -ForegroundColor Cyan
    }
    'logs' {
        Get-Content "${workingDirectory}\\logs\\daemon.log" -Tail 50 -Wait
    }
    'uninstall' {
        Stop-Service -Name \$ServiceName -ErrorAction SilentlyContinue
        nssm remove \$ServiceName confirm
        Write-Host "Service \$ServiceName uninstalled." -ForegroundColor Red
    }
}
`;

    // 5. README Installation Guide
    const readmeGuide = `# WhatsApp PHP Windows Service Installation Guide (ODBC SQL Server)

## Overview
This package wraps your WhatsApp synchronization PHP script into a continuous background Windows Service (daemon). It runs via **WinSW** or **NSSM**, executing your SQL Server ODBC queries every 30 seconds without browser timeouts or Apache/IIS page refresh limits.

## Option A: Using WinSW (Recommended)
1. Download **WinSW.exe** (rename it to \`${serviceName}.exe\`).
2. Place \`${serviceName}.exe\` and \`${serviceName}.xml\` in \`${workingDirectory}\`.
3. Open Command Prompt as **Administrator** and run:
   \`\`\`cmd
   ${serviceName}.exe install
   ${serviceName}.exe start
   \`\`\`

## Option B: Using NSSM (Non-Sucking Service Manager)
1. Download NSSM from [http://nssm.cc/](http://nssm.cc/).
2. Extract the archive and copy the \`nssm.exe\` file (from the \`win64\` folder) directly into the \`${workingDirectory}\` directory alongside your scripts.
3. Save and run the generated \`install-service.bat\` script as **Administrator** to install and start the service.
4. To remove the service later, run \`uninstall-service.bat\` as **Administrator**.

## Managing the Service via PowerShell
- **Check Status**: \`./manage-service.ps1 -Action status\`
- **View Live Logs**: \`./manage-service.ps1 -Action logs\`
- **Restart Service**: \`./manage-service.ps1 -Action restart\`
- **Uninstall Service**: \`./manage-service.ps1 -Action uninstall\`
`;

    // 6. Health Check Script (Optional)
    const healthCheckCode = `<?php
/**
 * Internal Health Check Script for ${serviceName}
 * Ping this script to confirm the daemon is responsive and database connectivity is active.
 */

header('Content-Type: application/json');

$response = [
    'service' => '${serviceName}',
    'status' => 'OK',
    'timestamp' => date('c'),
    'metrics' => [
        'memory_usage_mb' => round(memory_get_usage() / 1024 / 1024, 2)
    ]
];

// Optional: Add DB check here if required
// ...

echo json_encode($response);
?>`;

    const generatedFiles: any = {
      "winsw.xml": winswXml,
      "install-service.bat": nssmBatch,
      "uninstall-service.bat": nssmUninstallBatch,
      "whatsapp-daemon.php": phpDaemonCode,
      "manage-service.ps1": psScript,
      "README.md": readmeGuide
    };

    if (generateHealthCheck) {
      generatedFiles["health-check.php"] = healthCheckCode;
    }

    res.json({
      success: true,
      files: generatedFiles
    });
  } catch (err: any) {
    res.status(500).json({ success: false, error: err.message });
  }
});

// API: AI Assistant for PHP WhatsApp Sync & Windows Services
app.post("/api/ai-assist", async (req, res) => {
  try {
    const { prompt, context } = req.body;
    const apiKey = process.env.GEMINI_API_KEY;
    
    if (!apiKey) {
      return res.status(400).json({ 
        success: false, 
        error: "GEMINI_API_KEY is not configured. Please set it in AI Studio secrets." 
      });
    }

    const ai = new GoogleGenAI({ apiKey });
    
    const systemInstruction = `You are an expert Windows systems engineer and PHP developer specializing in running PHP ODBC daemons as robust Windows Services (using WinSW or NSSM) connecting to SQL Server for WhatsApp automation & synchronization units (AISensy, Askeva, Microgenn).`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: [
        { role: 'user', parts: [{ text: `Context: ${JSON.stringify(context || {})}\n\nQuestion/Request: ${prompt}` }] }
      ],
      config: {
        systemInstruction,
        temperature: 0.2,
      }
    });

    res.json({ success: true, text: response.text });
  } catch (err: any) {
    res.status(500).json({ success: false, error: err.message });
  }
});

// API: Real-time Health Check & Polling Endpoint
app.get("/api/health-check", (req, res) => {
  const serviceState = req.query.state || 'Running';
  
  // Simulate metrics based on state
  const isRunning = serviceState === 'Running';
  const memoryUsageMB = isRunning ? (22 + Math.floor(Math.random() * 8)) : 0;
  const cpuLoadPercent = isRunning ? (1 + Math.random() * 4).toFixed(1) : '0.0';
  
  res.json({
    success: true,
    status: serviceState, // 'Running', 'Stopped', 'Failed', 'Starting'
    metrics: {
      memoryUsageMB,
      cpuLoadPercent: parseFloat(cpuLoadPercent as string),
      odbcConnected: isRunning,
      queuePending: isRunning ? Math.floor(Math.random() * 3) : 0,
      uptimeSeconds: isRunning ? Math.floor(Date.now() / 1000) % 86400 : 0,
      lastPing: new Date().toLocaleTimeString(),
      errorRate: isRunning ? "0.0%" : "N/A"
    }
  });
});

// API: Simulate incoming WhatsApp webhook POST request to configured PHP daemon / script
app.post("/api/simulate-webhook", async (req, res) => {
  try {
    const {
      scriptPath = "C:\\whatsapp-sync\\daemon.php",
      phpPath = "C:\\php\\php.exe",
      payload,
      headers = {},
      eventType = "message_received"
    } = req.body;

    const startTime = Date.now();

    // Check payload validity
    let parsedPayload: any = null;
    try {
      parsedPayload = typeof payload === 'string' ? JSON.parse(payload) : payload;
    } catch {
      return res.status(400).json({
        success: false,
        statusCode: 400,
        statusText: "Bad Request",
        error: "Malformed JSON payload provided.",
        executionTimeMs: Date.now() - startTime
      });
    }

    if (!parsedPayload) {
      return res.status(400).json({
        success: false,
        statusCode: 400,
        statusText: "Bad Request",
        error: "Payload cannot be empty.",
        executionTimeMs: Date.now() - startTime
      });
    }

    // Extract common WhatsApp/AISensy fields
    const sender = parsedPayload?.entry?.[0]?.changes?.[0]?.value?.contacts?.[0]?.wa_id ||
                   parsedPayload?.from ||
                   parsedPayload?.phone ||
                   parsedPayload?.mobile ||
                   "+919876543210";
    
    const messageId = parsedPayload?.entry?.[0]?.changes?.[0]?.value?.messages?.[0]?.id ||
                      parsedPayload?.messageId ||
                      parsedPayload?.id ||
                      `wamid.HBgL${Date.now()}`;

    const textBody = parsedPayload?.entry?.[0]?.changes?.[0]?.value?.messages?.[0]?.text?.body ||
                     parsedPayload?.text ||
                     parsedPayload?.message ||
                     parsedPayload?.status ||
                     (parsedPayload?.event ? `Event: ${parsedPayload.event}` : "N/A");

    const hotelCode = parsedPayload?.hotelCode ||
                      parsedPayload?.hotel_code ||
                      parsedPayload?.Whatsapp_hotelcode ||
                      headers["X-WhatsApp-HotelCode"] ||
                      "DEFAULT";

    const hasMedia = Boolean(
      parsedPayload?.entry?.[0]?.changes?.[0]?.value?.messages?.[0]?.document ||
      parsedPayload?.media ||
      parsedPayload?.document ||
      parsedPayload?.pdf
    );

    const mediaFilename = parsedPayload?.entry?.[0]?.changes?.[0]?.value?.messages?.[0]?.document?.filename ||
                          parsedPayload?.media?.filename ||
                          (hasMedia ? "invoice_bill.pdf" : null);

    const statusValue = parsedPayload?.entry?.[0]?.changes?.[0]?.value?.statuses?.[0]?.status ||
                        parsedPayload?.status ||
                        "delivered";

    const executionLogs: string[] = [];
    const timestamp = new Date().toLocaleTimeString();
    
    executionLogs.push(`[${timestamp}] [HTTP-INBOUND] Received POST webhook dispatch target: ${scriptPath}`);
    executionLogs.push(`[${timestamp}] [HEADERS] Content-Type: ${headers['Content-Type'] || 'application/json'}, User-Agent: ${headers['User-Agent'] || 'AISensy-Webhook/2.0'}, Signature: VERIFIED_OK`);
    executionLogs.push(`[${timestamp}] [DAEMON-ROUTER] PHP worker (PID: 4820) spawned for event: ${eventType}`);
    executionLogs.push(`[${timestamp}] [PARSER] Hotel Code: [${hotelCode}] | Sender: [${sender}] | Message ID: [${messageId}]`);
    
    if (eventType === 'status_update') {
      executionLogs.push(`[${timestamp}] [STATUS-CALLBACK] Delivery status received: [${statusValue.toUpperCase()}] for message ${messageId}`);
      executionLogs.push(`[${timestamp}] [ODBC-EXEC] UPDATE tbl_Whatsapp_Outgoing SET DeliveryStatus='${statusValue}', UpdatedAt=GETDATE() WHERE MessageId='${messageId}'`);
    } else {
      executionLogs.push(`[${timestamp}] [INBOUND-MSG] Text: "${textBody.length > 40 ? textBody.substring(0, 40) + '...' : textBody}"`);
      if (hasMedia) {
        executionLogs.push(`[${timestamp}] [MEDIA-DISCOVERY] Attachment: ${mediaFilename} -> scheduled for PDF verification & local storage`);
      }
      executionLogs.push(`[${timestamp}] [ODBC-EXEC] INSERT INTO tbl_Whatsapp_Incoming (HotelCode, Sender, MessageId, Content, Status, CreatedAt) VALUES ('${hotelCode}', '${sender}', '${messageId}', '...', 'QUEUED', GETDATE())`);
    }
    
    executionLogs.push(`[${timestamp}] [ODBC-OK] Transaction committed successfully (1 row affected).`);
    executionLogs.push(`[${timestamp}] [HTTP-RESPONSE] Returning 200 OK to webhook source.`);

    const executionTimeMs = Math.max(16, Date.now() - startTime + Math.floor(Math.random() * 20));

    res.json({
      success: true,
      statusCode: 200,
      statusText: "OK",
      executionTimeMs,
      processedData: {
        eventType,
        sender,
        messageId,
        hotelCode,
        textBody,
        hasMedia,
        mediaFilename,
        deliveryStatus: eventType === 'status_update' ? statusValue : undefined,
        timestamp: new Date().toISOString()
      },
      logs: executionLogs,
      responseBody: {
        status: "success",
        acknowledged: true,
        messageId,
        processedAt: new Date().toISOString(),
        daemon: {
          script: scriptPath,
          php: phpPath,
          status: "PROCESSED_OK"
        }
      }
    });
  } catch (err: any) {
    res.status(500).json({
      success: false,
      statusCode: 500,
      statusText: "Internal Server Error",
      error: err.message || "Failed to process webhook POST"
    });
  }
});

async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`WhatsApp Windows Service Generator running on http://localhost:${PORT}`);
  });
}

startServer();
